# Generated by Django 5.2 on 2025-04-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('species', models.CharField(max_length=30, verbose_name='Вид')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='Snake', verbose_name='Фото')),
                ('birthdate', models.DateTimeField(verbose_name='Возраст')),
                ('poison', models.CharField(choices=[(0, 'Не яд'), (1, 'Яд')], verbose_name='Ядовитость')),
                ('gender', models.CharField(choices=[(0, 'Жен'), (1, 'Муж')], verbose_name='Пол')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
