# Generated by Django 5.2 on 2025-05-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snake',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
