# Generated by Django 5.2 on 2025-05-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_snake_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snake',
            name='gender',
            field=models.CharField(choices=[('0', 'Жен'), ('1', 'Муж')], verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='snake',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='snake',
            name='poison',
            field=models.CharField(choices=[('0', 'Не яд'), ('1', 'Яд')], verbose_name='Ядовитость'),
        ),
    ]
